---
- hosts: localhost
  become: true
  gather_facts: yes
  connection: local
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_type: plus
    nginx_rest_api_enable: true
    nginx_rest_api_port: 4321
    nginx_rest_api_write: true
    nginx_remove_license: false
    nginx_license:
      certificate: "/etc/ssl/nginx/nginx-repo.crt"
      key: "/etc/ssl/nginx/nginx-repo.key"
    nginx_modules:
      - njs
    
