---
- hosts: nginx
  become: true
  vars_files:
    - ~/ansible/vars/controller.yaml
  vars:
    nginx_type: plus
    nginx_enable: true
    nginx_start: true
    nginx_rest_api_enable: true
    nginx_rest_api_port: 4321
    nginx_rest_api_write: false
    nginx_license:
      certificate: "/etc/ssl/nginx/nginx-repo.crt"
      key: "/etc/ssl/nginx/nginx-repo.key"
    nginx_modules:
      njs: true

  tasks:

    - name: Copy over the NGINX Plus cert
      copy:
        src: /etc/ssl/nginx/nginx-repo.crt
        dest: /etc/ssl/nginx/
        owner: root
        group: root
        mode: 0444

    - name: Copy over the NGINX Plus key
      copy:
        src: /etc/ssl/nginx/nginx-repo.key
        dest: /etc/ssl/nginx/
        owner: root
        group: root
        mode: 0444

    - name: Run through the NGINX setup
      import_role:
        name: nginxinc.nginx

    - name: Setup Extended logging
      lineinfile:
        insertafter: "^http {.*"
        regexp: "    log_format main_ext.*"
        line: "    log_format main_ext '$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" \"$host\" sn=\"$server_name\" rt=$request_time ua=\"$upstream_addr\" us=\"$upstream_status\" ut=\"$upstream_response_time\" ul=\"$upstream_response_length\" cs=$upstream_cache_status';"
        path: /etc/nginx/nginx.conf

    - name: Enable Extended logging for access log
      lineinfile:
        regexp: "    access_log  /var/log/nginx/access.log.*"
        line: "    access_log  /var/log/nginx/access.log  main_ext;"
        path: /etc/nginx/nginx.conf

    - name: Ensure NGINX is Running
      service:
        name: nginx
        state: restarted
