---
- hosts: localhost
  become: true
  gather_facts: yes
  connection: local

  tasks:

  - name: Setup the certbot repository
    apt_repository:
      repo: ppa:certbot/certbot
      update_cache: yes

  - name: Install certbot package
    apt:
      name:
        - python-certbot-nginx

  - name: Setup Basic Auth File for API/Dash/Swagger access
    htpasswd:
      path: /home/ubuntu/secrets/htpasswd
      name: nginx
      password: "{{ lookup('password', '/home/ubuntu/secrets/basic_auth.passwd length=12') }}"
      owner: root
      group: nginx
      mode: 0640

  - name: Copy configs
    import_tasks: tasks/copy-configs.yaml

  - name: Remove the nginx default config file
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent

  - name: Setup Extended logging
    lineinfile:
      insertafter: "^http {.*"
      regexp: "    log_format main_ext.*"
      line: "    log_format main_ext '$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" \"$host\" sn=\"$server_name\" rt=$request_time ua=\"$upstream_addr\" us=\"$upstream_status\" ut=\"$upstream_response_time\" ul=\"$upstream_response_length\" cs=$upstream_cache_status';"
      path: /etc/nginx/nginx.conf

  - name: Enable Extended logging for access log
    lineinfile:
      regexp: "    access_log  /var/log/nginx/access.log.*"
      line: "    access_log  /var/log/nginx/access.log  main_ext;"
      path: /etc/nginx/nginx.conf

  - name: Setup certbot
    shell:
      cmd: certbot -n --register-unsafely-without-email --agree-tos register
      creates: /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org

  - name: Check for Certifcate Expiry (within 7 days)
    shell: |
      openssl x509 -in "/etc/letsencrypt/live/{{ wsid }}.{{ domain }}/cert.pem" -checkend 604800
    ignore_errors: true
    register: cert_status

  - name: Renew/Generate Certificates
    shell: |
      certbot -n --renew-with-new-domains \
      --nginx \
      --cert-name {{wsid}}.{{ domain }} \
      -d {{wsid}}.{{ domain }} \
      -d devportal.{{wsid}}.{{ domain }} \
      -d www.{{wsid}}.{{ domain }} \
      -d app.{{wsid}}.{{ domain }} \
      -d api.{{wsid}}.{{ domain }} \
      -d ctrl.{{wsid}}.{{ domain }} \
      -d git.{{wsid}}.{{ domain }} \
      -d k8s.{{wsid}}.{{ domain }} \
      -d graf.{{wsid}}.{{ domain }} \
      -d prom.{{wsid}}.{{ domain }} \
      -d jenkins.{{wsid}}.{{ domain }}
    when: cert_status.rc != 0

  - name: Copy configs
    import_tasks: tasks/copy-configs.yaml

  - name: Set custom index page
    template:
      src: conf.d/wild-index.j2
      dest: /usr/share/nginx/html/index.html

  - name: Restart NGINX
    service:
      name: nginx
      state: restarted

