# Ansible variable configuration
---

cicd:
  git:
    hostname: cicd.multipass.test
    admin_username: nginx
    admin_password: "{{ lookup('password', '~/git.passwd length=12') }}"
    deploy_repos: no


  jenkins:
    hostname: cicd.multipass.test
    http_port: 8080
    url_prefix: /
    proxy_url: https://jenkins.mboddington.nginx/
    admin_username: nginx
    admin_password: "{{ lookup('password', '~/jenkins.passwd length=12') }}"

