---
openapi: 3.0.0
servers:
  - description: Internet Chuck Norris Databas
    url: https://api.icndb.com
info:
  description: This is a simple API for Chuck Norris
  version: "1.0.0"
  title: Simple ICNDB API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /jokes/random:
    get:
      tags:
        - developers
      summary: Gets a random joke from the database
      operationId: jokeRandom
      description: |
        Gets a random Chuck Norris Joke
      parameters:
        - in: query
          name: firstName
          description: pass an optional firstName for changing the person the joke is about
          required: false
          schema:
            type: string
        - in: query
          name: lastName
          description: pass an optional lastName for changing the person the joke is about
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A random joke
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Joke'
        '400':
          description: bad input parameter

components:
  schemas:
    Joke:
      type: object
      required:
        - type
        - value
      properties:
        type:
          type: string
          example: success
        value:
          $ref: '#/components/schemas/JokeValue'
    JokeValue:
      type: object
      required:
        - id
        - joke
      properties:
        joke:
          type: string
          example: "Time waits for no man. Unless that man is Chuck Norris."
        id:
          type: integer
          format: int32

