---
- hosts: controller
  become: yes
  vars_files:
    - ~/ansible/vars/controller.yaml
  tasks:

    - name: Install Required Packages
      apt:
        name:
          - jq
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Checking for kubernetes install on host
      stat:
        path: /usr/bin/kubectl
      register: kubectl_binary

    - name: Checking for existing controller deployment
      block:
        - name: Check for nginx-controller frontend deployment
          shell:
            argv:
              - "kubectl"
              - "get"
              - "deployment/frontend"
              - "--namespace=nginx-controller"
              - "--output=yaml"
          register: deployment
          ignore_errors: yes
  
        - name: Detect installed version from frontend deployment
          shell:
            cmd: "jq .spec.template.spec.containers[0].image | cut -d: -f 2 | cut -d . -f 1,2"
            stdin: "{{ deployment.stdout }}"
          register: deployment_version
          when: deployment.stdout | length > 0
  
      when: kubectl_binary.stat.exists == True
      
    - name: Register installed controller version
      set_fact:
        controller_installed_version: "{{ deployment_version.stdout | default('0.0') }}"
        cacheable: yes

    - name: Installing Controller
      block:

        - name: Copy ths installer to the system
          become: no
          unarchive:
            src: "{{ controller.install_package }}"
            dest: "/home/{{ ansible_ssh_user }}/"
            creates: "/home/{{ ansible_ssh_user }}/controller-installer"

        - name: Execute the installer
          become: no
          command:
            chdir: "/home/{{ ansible_ssh_user }}/controller-installer"
            cmd: |
              ./install.sh -y -n --smtp-host localhost --smtp-port 25 --smtp-authentication false --smtp-use-tls false
              --noreply-address noreply@f5.com --admin-email {{ controller.admin_email }}
              --admin-password {{ controller.admin_password }}
              --fqdn {{ controller.hostname }}
              --auto-install-docker --self-signed-cert --organization-name 'F5 - NGINX'
              --admin-firstname {{ controller.admin_firstname }}
              --admin-lastname {{ controller.admin_lastname }}
              --tsdb-volume-type local

      when: controller_installed_version != controller.version



