---
- hosts: nginx
  become: true
  roles:
    - role: nginxinc.nginx
  vars_files:
    - ~/ansible/vars/controller.yaml
  vars:
    nginx_type: plus
    nginx_enable: true
    nginx_start: true
    nginx_license:
      certificate: "/etc/ssl/nginx/nginx-repo.crt"
      key: "/etc/ssl/nginx/nginx-repo.key"
    nginx_modules:
      njs: true

  tasks:

    - name: Ensure NGINX is Running
      service:
        name: nginx
        state: restarted

    - name: Login to the controller
      import_tasks: tasks/login.yaml

    - name: Fetch Globals fron controller
      import_tasks: tasks/fetch_globals.yaml

    - name: License the NGINX instances
      import_tasks: tasks/install_agents.yaml

