---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www-whatcheese-web-ingress
  namespace: cheese-demo
  annotations:
    nginx.org/lb-method: "sound_robin"
spec:
  ingressClassName: nginx
  rules:
  - host: "www.ws08.ngxlab.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whatcheese-web-v2
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-whatcheese-web-ingress
  namespace: cheese-demo
  annotations:
    #custom.nginx.org/oidc:  "on"
spec:
  ingressClassName: nginx
  rules:
  - host: "api.ws08.ngxlab.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whatcheese-api
            port:
              number: 80
