---
  - name: Login to the controller if necessary
    import_tasks: login.yaml
    when: nginx_controller_session is not defined

  - name: Fetch the Globals from the controller
    uri:
      url: https://{{ controller.hostname }}/api/{{ controller.api_version }}/platform/global
      method: GET
      headers:
        Cookie: "session={{ nginx_controller_session.cookies.session }}"
      status_code: 200
      validate_certs: False
    register: globals

  - name: Set ctrl_globals fact
    set_fact:
      ctrl_globals: "{{ globals.json.currentStatus }}"

