---
  - name: Login to the controller
    uri:
      url: https://{{ controller.hostname }}/api/{{ controller.api_version }}/platform/login
      method: POST
      body_format: json 
      body: 
        credentials: 
          type: "BASIC"
          username: "{{ controller.admin_email }}"
          password: "{{ controller.admin_password }}"
      status_code: 204
      validate_certs: False
    register: session

  - name: Store session cookie as fact
    set_fact:
      nginx_controller_session: "{{ session }}"
  
