= Task 3: Primer
:showtitle:
:toc: left
:sectlinks:
:prev_section: task2
:next_section: task4
:source-highlighter: pygments

****
<<index.adoc#,Contents>> +
<<task2.adoc#,Previous Task>> +
<<task4.adoc#,Next Task>> +
****

== 3.1 Primer

NGINX Plus ships with a few basic HTML pages, and some other goodies, and that makes it easy for
us to test the web server use case. First, we need to understand the config file structure of NGINX
Plus.

NGINX and NGINX Plus are similar to other services in that they use a text‑based configuration file
written in a particular format. By default, the file is named nginx.conf and for NGINX Plus is placed in
the `/etc/nginx` directory. (For NGINX Open Source, the location depends on the package system used
to install NGINX and the operating system. It is typically one of `/usr/local/nginx/conf`, `/etc/nginx`, or
`/usr/local/etc/nginx`.)

The configuration file consists of directives and their parameters. Simple (single‑line) directives each
end with a semicolon. Other directives act as “containers” that group together related directives,
enclosing them in curly braces ( {} ); these are often referred to as blocks

== 3.2 Simple Directives

----
user                    nobody;
error_log               logs/error.log notice;
worker_processes        1;
----

To make the configuration easier to maintain, it is recommended that we split it into a set of
feature‑specific files stored in the `/etc/nginx/conf.d` directory and use the include directive in the
main `nginx.conf` file to reference the contents of the feature‑specific files:

----
include     conf.d/http;
include     conf.d/stream;
include     conf.d/exchange-enhanced;
----

A few top‑level directives, referred to as contexts, group together the directives that apply to
different traffic types:

* events – General connection processing
* http – HTTP traffic
* mail – Mail traffic
* stream – TCP and UDP traffic

Directives placed outside of these contexts are said to be in the main context.

== 3.3 Contexts

The following configuration illustrates the use of contexts:

----
user nobody; # a directive in the 'main' context

events {
  # configuration of connection processing
}

http {
  # Configuration specific to HTTP and affecting all virtual servers

  server {
    # configuration of HTTP virtual server 1

    location /one {
      # configuration for processing URIs starting with '/one'
    }

   location /two {
     # configuration for processing URIs starting with '/two'
   }

  }

  server {
    # configuration of HTTP virtual server 2
  }
}

stream {
  # Configuration specific to TCP/UDP and affecting all virtual servers
  server {
    # configuration of TCP virtual server 1
  }
}

----

In general, a child context – one contained within another context (its parent) – inherits the settings
of directives included at the parent level. Some directives can appear in multiple contexts, in which
case you can override the setting inherited from the parent by including the directive in the child
context.

Now let's move on to our using NGINX as a webserver <<task4.adoc#,Task 4>> 

|===
|<<task2.adoc#,Previous>>|<<task4.adoc#,Next Task>>
|===



