= Task 1: Familiarize yourself with Ansible
:showtitle:
:toc: left
:sectlinks:
:prev_section: index
:next_section: task2

****
<<index.adoc#,Top>> +
<<task1.adoc#,Previous Task>> +
<<task2.adoc#,Next Task>> +
****

== Introduction

Ansible is an automation tool from RedHat which supports agentless configuration of remote systems.
Ansible can be used on the command line to execute *"Ad-Hoc"* commands, or whole sequencies of configuration
steps can be grouped and executed together in what is known as a *"playbook"*.

The system from which you run ansible tasks is called the  *"control node"*. This system has ansible
installed locally, and it is used to execute tasks on *"managed nodes"* (also known as hosts).

The hosts do not need to have ansible installed. Ansible is agent-less. However, all of the hosts which 
are managed by the ansible control node need to be defined in your *"inventory"*. 

An inventory item can be a single host or a group of hosts.
When you execute an ansible task against a host or group in your inventory, ansible performs the operation
remotely (from the control node) using *"modules"*.

There are hundreds of ansible modules available each with a particular purpose. Ansible modules can do anything from
deploying host Operating Systems, managing users groups and files, through to managing configuration of an F5 Big-IP.

****
In this course you will be connecting to a machine running on Amazon EC2. This host is publically
accessable via SSH/HTTP/HTTPS. You will be provided a FQDN and a SSH private key for access. +
This machine is your Ansible Control Node, and your "frontend" for all other systems
****

'''

== Running Ansible

In your home directory, you have a directory called ansible. We will be executing all of your ansible
tasks and playbooks from this location. When you execute ansible it checks for an _ansible.cfg_ file
in the local folder first, followed by various other locations, finally falling back to _/etc/ansible.cfg_.

As you've probably guessed, the ansible.cfg file we are using for this workshop resides in your
_~/ansible_ folder, and running commands outside of this folder will not work as expected.

'''

== Take a look at your ansible configuration

The ansible.cfg file in your ansible folder contains all of the ansible defaults.
We're only setting a handful:

----
$ egrep -v "^[\[#]" ansible.cfg | sort -u
  
host_key_checking = False
inventory      = inventory
nocows = 1
remote_user = ubuntu
----

We set the remote user to be *"ubuntu"*, so when ansible attempts to execute a command it will try to ssh
to the remote system as ubuntu. We set nocows to 1, which disables cowsay, but feel free to re-enable it
if you find it comforting. Finally we set the location of the inventory file.

The inventory can be a script to generate hosts/groups dynamically, but in our case a simple static text
file will suffice.

'''

Next we can take a look at the inventory

----
$ cat inventory
localhost
gateway
  
[controller]
ctrl1
  
 ...
  
[remote]
ctrl1
nginx1
nginx2
unit1
unit2
cicd1
----

Ansible uses the inventory to match hosts and groups of hosts on which to execute tasks or playbooks.

'''

== Ansible Ad-hoc mode
Ansible allows you to execute tasks in an ad-hoc way. Try executing the following:

----
$ ansible -m ping ctrl1
$ ansible -m ping nginx
----

The above command line executed the 'ping' module against the provided inventory item.
The first ping command was execute on a single host 'ctrl1', while the second was executed on
all hosts in the group 'nginx'

The ansible 'ping' module is a very simple module and it simply confirms that you can connect to the
host in the inventory, and execute a command.
Most modules take additional arguments, try running:

----
$ ansible -m copy localhost -a "src=/etc/hosts dest=/home/ubuntu/hosts"
----

The above uses the copy module, which requires additional arguments. The _dest_ argumnet is mandatory
and tells ansible where to copy the given content.
The content can be read from a file in which case the _src_ argument is used. Or it may be given to
the module directly with the _content_ argument.

Here we simply copied the /etc/hosts file into your home directory.

'''

== Ansible Facts

Ansible can also gather facts about the nodes on which it executes. These facts include the
Operating System details, information on network interfaces, etc.

The facts can be collected using the setup module. Try:

----
$ ansible -m setup localhost
----

You will have just seen a whole load of information flash through your console.

Fortunately the setup module has a filter argument. Try:

----
$ ansible -m setup nginx -a "filter=ansible_dist*"
----

'''

== Ansible Playbooks

In the previous section we used ansible to execute single tasks using the specified modules.
A more common requirement is to have ansible execute a sequence of tasks in order.
This is where a playbook comes in.

A Playbook is an ordered list of tasks to execute against a set of hosts.
It has several advantages over Ad-Hoc mode:

 * You can include variables either directly or from extertnal sources.
 * You can use loops to perform tasks multiple times (eg iterate over a list of users)
 * You can use conditional statements to determine if a task needs to be run
 * You can start a task asynchronously and poll for completion
 * You can use other tasks from Ansible Roles.

'''

== Finishing our configuration

The machines that you are connecting to for this workshop have all been deployed using Ansible. +
However the set up is not complete, 

== Ansible Roles

An Ansible Role is a group of tasks and variables which have been built in a standard way to enable reuse.
It's a good way to create building blocks for performing common tasks, such as setting up
a webserver, or installing a system such as jenkins. Unlike a playbook a role is not tied to a group of hosts.

We're going to be making use of a few ansible roles during this course.

Ansible includes a tool to search and install community published roles called _ansible-galaxy_.
Lets use ansible-galaxy to install the NGINX role published by F5/NGINX.

----
$ ansible-galaxy install nginxinc.nginx
----

We'll make use of this role in task2.

