# Ansible variable configuration
---

  specs_dir: ~/ansible/specs
  jwks_dir: ~/ansible/jwks
  envs_dir: ~/ansible/envs
  certs_dir: ~/ansible/certs

  env: f1_prod

  controller:
    api_version: "v1"
    hostname: ctrl.{{ wsid }}.{{ domain }}
    admin_email: admin@nginx.com
    admin_password: "{{ lookup('password', '~/secrets/controller.passwd length=12') }}"
    remove_failed: true


