---
kind: Service
apiVersion: v1
metadata:
  name: ingress-service
  namespace: nginx-ingress
spec:
  selector:
    app: nginx-ingress
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 30443
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
